name: auto-update

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  update-jplocalgov-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: update jplocalgov data
        run: bundle exec rake jplocalgov:data:update_all
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          branch: update_jplocalgov_data
          branch-suffix: timestamp
          delete-branch: true
          title: bundle exec rake jplocalgov:data:update_all
          commit-message: bundle exec rake jplocalgov:data:update_all
